name: truconsent_consent_notice_flutter
description: Flutter SDK for TruConsent consent banner. This package provides native Flutter widgets for displaying and managing consent banners in Flutter applications.
version: 0.1.2
homepage: https://github.com/truconsent/truconsent-banner-flutter-sdk
repository: https://github.com/truconsent/truconsent-banner-flutter-sdk
issue_tracker: https://github.com/truconsent/truconsent-banner-flutter-sdk/issues
license: MIT

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.1.1
  intl: ^0.20.2
  uuid: ^4.3.0
  url_launcher: ^6.2.0
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

